### ISSUE TITLE
Clean up code

### ISSUE THREAD

**Issue by demonno** [demonno/ertaoz-bot#2]
Remove following 

* noshrevan
* qristefore
* ertaoz 
  * Remove all related to `pickledb`
  * `unleash_spongebob`
  * `TEST_GROUP_ID` and `NONAME_GROUP_ID` usages
  * `unleash_spongebob` command
  * `restrain_spongebob` command
  * `add_error_handler` remove error handler 
  * remove about

**Comment by MadViper** [comment]
We should also remove [contributirs.py](https://github.com/demonno/ertaoz-bot/blob/master/contributors.py)
